SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `ACCOUNT_DETAIL_SCHEMAS` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `ACCOUNT_DETAIL_SCHEMAS` ;

-- -----------------------------------------------------
-- Table `ACCOUNT_DETAIL_SCHEMAS`.`ACCOUNT_DETAIL`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `ACCOUNT_DETAIL_SCHEMAS`.`ACCOUNT_DETAIL` (
  `ACCOUNT_ID` VARCHAR(10) NOT NULL ,
  `ACCOUNT_NAME` VARCHAR(50) NULL ,
  `LAST_UPDATE_TIME` TIMESTAMP NULL ,
  PRIMARY KEY (`ACCOUNT_ID`) )
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
